{
 "title": "Subgraph Indexing Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "subgraph_hash",
    "query": "select subgraph from deployment_schemas where id > 0"
   },
   {
    "name": "handler",
    "query": "label_values(subgraph_handler_execution_time_[[subgraph_hash]]_bucket, handler)"
   },
   {
    "name": "host_fn",
    "query": "label_values(subgraph_host_fn_execution_time_[[subgraph_hash]]_bucket, host_fn_name)"
   },
   { "name": "network", "query": "ethereum_chain_head_number" }
  ]
 },
 "panels": [
  {
   "title": "Time spent while indexing",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase([[subgraph_hash]]_sync_total_secs[1y]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_unknown_secs[1y]))",
     "legendFormat": "unknown"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_scan_blocks_secs[1y]))",
     "legendFormat": "scan_blocks"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_module_init_secs[1y]))",
     "legendFormat": "module_init"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_run_handler_secs[1y]))",
     "legendFormat": "run_handler"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_transact_block_secs[1y]))",
     "legendFormat": "transact_block"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_host_export_other_secs[1y]))",
     "legendFormat": "host_export_other"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_host_export_store_get_secs[1y]))",
     "legendFormat": "host_export_store_get"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_host_export_store_set_secs[1y]))",
     "legendFormat": "host_export_store_set"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_host_export_ethereum_call_secs[1y]))",
     "legendFormat": "host_export_ethereum_call"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_host_export_ipfs_cat_secs[1y]))",
     "legendFormat": "host_export_ipfs_cat"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_host_export_ipfs_map_secs[1y]))",
     "legendFormat": "host_export_ipfs_map"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_store_get_asc_new_secs[1y]))",
     "legendFormat": "store_get_asc_new"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_apply_entity_modifications_secs[1y]))",
     "legendFormat": "apply_entity_modifications"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_check_interface_entity_uniqueness_secs[1y]))",
     "legendFormat": "check_interface_entity_uniqueness"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_apply_entity_modifications_update_secs[1y]))",
     "legendFormat": "apply_entity_modifications_update"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_apply_entity_modifications_insert_secs[1y]))",
     "legendFormat": "apply_entity_modifications_insert"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_as_modifications_secs[1y]))",
     "legendFormat": "as_modifications"
    },
    {
     "expr": "sum(increase([[subgraph_hash]]_entity_cache_evict_secs[1y]))",
     "legendFormat": "entity_cache_evict"
    }
   ]
  },
  {
   "title": "Eth Rpc Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests per minute" }
   ],
   "targets": [
    {
     "expr": "sum(increase(subgraph_eth_rpc_request_duration_[[subgraph_hash]][1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Reverted Blocks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(subgraph_reverted_blocks_[[subgraph_hash]][1m])",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Total time waiting for DB connection",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "[[subgraph_hash]]_get_entity_conn_secs"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "content": "<br/> \n<center> \n  <h1>Block Processing / Handler Execution</h1> \n</center>"
  },
  {
   "title": "Blocks Processed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(subgraph_block_processing_duration_[[subgraph_hash]]_sum[1m]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Block Processing Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(increase(subgraph_block_processing_duration_[[subgraph_hash]]_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Transact Block Ops Duration",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(subgraph_transact_block_operations_duration_[[subgraph_hash]]_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "[[host_fn]] Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(increase(subgraph_host_fn_execution_time_[[subgraph_hash]]_bucket{host_fn_name=\"[[host_fn]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Host Function Triggered",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(subgraph_host_fn_execution_time_[[subgraph_hash]]_sum[1m])) by (host_fn_name)",
     "legendFormat": "{{host_fn_name}}"
    }
   ]
  },
  {
   "title": "Block Trigger Count",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(increase(subgraph_block_trigger_count_[[subgraph_hash]]_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "[[handler]] Execution Time",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(increase(subgraph_handler_execution_time_[[subgraph_hash]]_bucket{handler=\"[[handler]]\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Handler Triggered",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(subgraph_handler_execution_time_[[subgraph_hash]]_sum[1m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 64 },
   "content": "</br>\n<center> \n  <h1>GraphQL Server</h1> \n</center>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 64 },
   "content": "<br/> \n<center> \n  <h1>Block Ingestor</h1> \n</center>"
  },
  {
   "title": "Query Execution Time Histogram ([[subgraph_hash]])",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(subgraph_query_execution_time_bucket{subgraph_deployment=\"[[subgraph_hash]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query Execution Time Histogram ([[subgraph_hash]])",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 66 },
   "repeat": "subgraph_hash",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(subgraph_query_execution_time_bucket{subgraph_deployment=\"[[subgraph_hash]]\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "type": "table",
   "description": "block_ingestor_panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "targets": [
    { "expr": "ethereum_chain_head_number", "legendFormat": "{{network}}" }
   ]
  },
  {
   "title": "Block Syncing Rate",
   "type": "graph",
   "description": "block_ingestor_panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ethereum_chain_head_number{kubernetes_pod_name=\"index-node-block-ingestor-0\"}[1m])) by (network)",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Queries  (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(increase(subgraph_query_execution_time_count[1m])) by (subgraph_deployment)",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  },
  {
   "title": "Query Rate (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "locale", "label": "Queries per minute per minute" }
   ],
   "targets": [
    {
     "expr": "sum(rate(subgraph_query_execution_time_count[1m])) by (subgraph_deployment)",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  },
  {
   "title": "Failed Queries  (All Subgraphs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "increase(subgraph_query_failed_execution_time_count[1m])",
     "legendFormat": "{{subgraph_deployment}}"
    }
   ]
  }
 ]
}