version: "3"
services:
  indexer-service:
    image: graphprotocol/indexer-service:latest
    ports:
      - "7600:7600"
      - "7300:7300"
    environment:
      INDEXER_SERVICE_PORT: '7600'
      INDEXER_SERVICE_GRAPH_NODE_QUERY_ENDPOINT: 'http://[IP]:8000/' # replace [IP]
      INDEXER_SERVICE_GRAPH_NODE_STATUS_ENDPOINT: 'http://[IP]:8030/graphql' # replace [IP]
      INDEXER_SERVICE_NETWORK_SUBGRAPH_ENDPOINT: 'https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-rinkeby'
      INDEXER_SERVICE_ETHEREUM: 'https://rinkeby.infura.io/v3/[project ID]' #replace [project ID]
      INDEXER_SERVICE_MNEMONIC: '*** ***** *****'
      SERVER_HOST: '[IP]'  # replace [IP]
      SERVER_PORT: '5432'
      SERVER_DB_NAME: 'user'        #provide DB user
      SERVER_DB_USER: 'DB'          #provide DB name
      SERVER_DB_PASSWORD: 'passwd'  #provide DB password
    restart: always	
  indexer-agent:
    image: graphprotocol/indexer-service:latest
    ports:
          - "8200:8000"
          - "8220:8020"
          - "8230:8030"
          - "18000:18000"
    environment:
      INDEXER_SERVICE_GRAPH_NODE_QUERY_ENDPOINT: 'http://[IP]:8000/' # replace [IP]
      INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT: 'http://[IP]:8020/'    # replace [IP]
      INDEXER_SERVICE_GRAPH_NODE_STATUS_ENDPOINT: 'http://[IP]:8030/graphql' # replace [IP]
      INDEXER_AGENT_PUBLIC-INDEXER-URL: 'URL' # replace URL
      INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT: 'https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-rinkeby'
      INDEXER_AGENT_INDEX_NODE_IDS: 'default' #Makes ure it match the node ID when the subgraphs are initiated '["default", "subgraph_uniswap", "subgraph_synthetixio", "subgraph_gravity"]'
      INDEXER_AGENT_INDEXER-MANAGEMENT-PORT: '18000'
      INDEXER_AGENT_ETHEREUM: 'https://rinkeby.infura.io/v3/[project ID]' #replace [project ID]
      INDEXER_AGENT_MNEMONIC: '*** ***** *****'
      INDEXER_AGENT_POSTGRES-HOST: '[IP]'   # replace [IP]
      INDEXER_AGENT_POSTGRES-PORT: '5432'
      INDEXER_AGENT_POSTGRES_DATABASE: 'DB'     #provide DB name
      INDEXER_AGENT_POSTGRES-USERNAME: 'user'   #provide DB user
      INDEXER_AGENT_POSTGRES-PASSWORD: 'passwd' #provide DB password
    restart: always
